CREATE TABLE IF NOT EXISTS public.caen (
    code character varying(7) PRIMARY KEY,
    name character varying(500)
);

delete from public.caen;

INSERT INTO public.caen (code, name)
VALUES
('A','Agricultură, silvicultură și pescuit'),
('01','Agricultură, vânătoare și servicii anexe'),
('011','Cultivarea plantelor nepermanente'),
('0111','Cultivarea cerealelor (exclusiv orez), plantelor leguminoase și a plantelor producătoare de semințe oleaginoase'),
('0112','Cultivarea orezului'),
('0113','Cultivarea legumelor și a pepenilor, a rădăcinoaselor și tuberculilor'),
('0114','Cultivarea trestiei de zahăr'),
('0115','Cultivarea tutunului'),
('0116','Cultivarea plantelor pentru fibre textile'),
('0119','Cultivarea altor plante din culturi nepermanente'),
('012','Cultivarea plantelor din culturi permanente'),
('0121','Cultivarea strugurilor'),
('0122','Cultivarea fructelor tropicale si subtropicale'),
('0123','Cultivarea fructelor citrice'),
('0124','Cultivarea fructelor semintoase si samburoase'),
('0125','Cultivarea fructelor arbuștilor fructiferi, capsunilor, nuciferilor si a altor pomi fructiferi'),
('0126','Cultivarea fructelor oleaginoase'),
('0127','Cultivarea plantelor pentru prepararea băuturilor'),
('0128','Cultivarea condimentelor, plantelor aromatice, medicinale si a plantelor de uz farmaceutic'),
('0129','Cultivarea altor plante permanente'),
('013','Cultivarea plantelor pentru inmultire'),
('0130','Cultivarea plantelor pentru inmultire'),
('014','Creșterea animalelor'),
('0141','Creșterea bovinelor de lapte'),
('0142','Creșterea altor bovine'),
('0143','Creșterea cailor si a altor cabaline'),
('0144','Creșterea camilelor si a camelidelor'),
('0145','Creșterea ovinelor si caprinelor'),
('0146','Creșterea porcinelor'),
('0147','Creșterea pasarilor'),
('0149','Creșterea altor animale'),
('015','Activități in ferme mixte (cultura vegetala combinata cu creșterea animalelor)'),
('0150','Activități in ferme mixte (cultura vegetala combinata cu creșterea animalelor)'),
('016','Activități auxiliare agriculturii si activități după recoltare'),
('0161','Activități auxiliare pentru producția vegetala'),
('0162','Activități auxiliare pentru creșterea animalelor'),
('0163','Activități după recoltare'),
('0164','Pregatirea semințelor'),
('017','Vanatoare, capturarea cu capcane a vanatului si activități de servicii anexe vanatorii'),
('0170','Vanatoare,capturarea cu capcane a vanatului si activități de servicii anexe vanatorii'),
('02','Silvicultură și exploatare forestieră'),
('021','Silvicultura si alte activități forestiere'),
('0210','Silvicultura si alte activități forestiere'),
('022','Exploatarea forestiera'),
('0220','Exploatarea forestiera'),
('023','Colectarea produselor forestiere nelemnoase din flora spontana'),
('0230','Colectarea produselor forestiere nelemnoase din flora spontana'),
('024','Activități de servicii anexe silviculturii'),
('0240','Activități de servicii anexe silviculturii'),
('03','Pescuitul și acvacultura'),
('031','Pescuitul'),
('0311','Pescuitul maritim'),
('0312','Pescuitul in ape dulci'),
('032','Acvacultura'),
('0321','Acvacultura maritima'),
('0322','Acvacultura in ape dulci'),
('B','Industria extractivă'),
('05','Extracția cărbunelui superior și inferior'),
('051','Extracția carbunelui superior (PCS=>23865 kJ/kg)'),
('0510','Extracția carbunelui superior (PCS=>23865 kJ/kg)'),
('052','Extracția carbunelui inferior (PCS<23865 kJ/kg)'),
('0520','Extracția carbunelui inferior (PCS'),
('06','Extracția petrolului brut și a gazelor naturale'),
('061','Extracția petrolului brut'),
('0610','Extracția petrolului brut'),
('062','Extracția gazelor naturale'),
('0620','Extracția gazelor naturale'),
('07','Extracția minereurilor metalifere'),
('071','Extracția minereurilor feroase'),
('0710','Extracția minereurilor feroase'),
('072','Extracția minereurilor metalifere neferoase'),
('0721','Extracția minereurilor de uraniu si toriu'),
('0729','Extracția altor minereuri metalifere neferoase'),
('08','Alte activități extractive'),
('081','Extracția pietrei, nisipului si argilei'),
('0811','Extracția pietrei ornamentale si a pietrei pentru construcții, extracția pietrei calcaroase, ghipsului, cretei si a ardeziei'),
('0812','Extracția pietrisului si nisipului; extracția argilei si caolinului'),
('089','Alte activități extractive n.c.a.'),
('0891','Extracția mineralelor pentru industria chimica si a ingrasamintelor naturale'),
('0892','Extracția turbei'),
('0893','Extracția sarii'),
('0899','Alte activități extractive n.c.a.'),
('09','Activități de servicii anexe extracției'),
('091','Activități de servicii anexe extracției petrolului brut si gazelor naturale'),
('0910','Activități de servicii anexe extracției petrolului brut si gazelor naturale'),
('099','Activități de servicii anexe pentru extracția mineralelor'),
('0990','Activități de servicii anexe pentru extracția mineralelor'),
('C','Industria prelucrătoare'),
('10','Industria alimentară'),
('101','Producția, prelucrarea si conservarea carnii si a produselor din carne'),
('1011','Prelucrarea si conservarea carnii'),
('1012','Prelucrarea si conservarea carnii de pasare'),
('1013','Fabricarea produselor din carne (inclusiv din carne de pasare)'),
('102','Prelucrarea si conservarea pestelui, crustaceelor si molustelor'),
('1020','Prelucrarea si conservarea pestelui, crustaceelor si molustelor'),
('103','Prelucrarea si conservarea fructelor si legumelor'),
('1031','Prelucrarea si conservarea cartofilor'),
('1032','Fabricarea sucurilor de fructe si legume'),
('1039','Prelucrarea si conservarea fructelor si legumelor n.c.a.'),
('104','Fabricarea uleiurilor si a grasimilor vegetale si animale'),
('1041','Fabricarea uleiurilor si grasimilor'),
('1042','Fabricarea margarinei si a altor produse comestibile similare'),
('105','Fabricarea produselor lactate'),
('1051','Fabricarea produselor lactate si a branzeturilor'),
('1052','Fabricarea inghetatei'),
('106','Fabricarea produselor de morarit, a amidonului si produselor din amidon'),
('1061','Fabricarea produselor de morarit'),
('1062','Fabricarea amidonului si a produselor din amidon'),
('107','Fabricarea produselor de brutarie si a produselor fainoase'),
('1071','Fabricarea painii; fabricarea prajiturilor si a produselor proaspete de patiserie'),
('1072','Fabricarea biscuitilor si piscoturilor; fabricarea prajiturilor si a produselor conservate de patiserie'),
('1073','Fabricarea macaroanelor, taiteilor, cus-cus-ului si a altor produse fainoase similare'),
('108','Fabricarea altor produse alimentare'),
('1081','Fabricarea zaharului'),
('1082','Fabricarea produselor din cacao, a ciocolatei si a produselor zaharoase'),
('1083','Prelucrarea ceaiului si cafelei'),
('1084','Fabricarea condimentelor si ingredientelor'),
('1085','Fabricarea de mancaruri preparate'),
('1086','Fabricarea preparatelor alimentare omogenizate si alimentelor dietetice'),
('1089','Fabricarea altor produse alimentare n.c.a.'),
('109','Fabricarea preparatelor pentru hrana animalelor'),
('1091','Fabricarea preparatelor pentru hrana animalelor de ferma'),
('1092','Fabricarea preparatelor pentru hrana animalelor de companie'),
('11','Fabricarea băuturilor'),
('110','Fabricarea băuturilor'),
('1101','Distilarea, rafinarea si mixarea băuturilor alcoolice'),
('1102','Fabricarea vinurilor din struguri'),
('1103','Fabricarea cidrului si a altor vinuri din fructe'),
('1104','Fabricarea altor bauturi nedistilate, obținute prin fermentare'),
('1105','Fabricarea berii'),
('1106','Fabricarea maltului'),
('1107','Producția de bauturi racoritoare nealcoolice; producția de ape minerale si alte ape imbuteliate'),
('12','Fabricarea produselor din tutun'),
('120','Fabricarea produselor din tutun'),
('1200','Fabricarea produselor din tutun'),
('13','Fabricarea produselor textile'),
('131','Pregatirea fibrelor si filarea fibrelor textile'),
('1310','Pregatirea fibrelor si filarea fibrelor textile'),
('132','Producția de tesaturi'),
('1320','Producția de tesaturi'),
('133','Finisarea materialelor textile'),
('1330','Finisarea materialelor textile'),
('139','Fabricarea altor articole textile'),
('1391','Fabricarea de metraje prin tricotare sau crosetare'),
('1392','Fabricarea de articole confectionate din textile (cu excepția imbracamintei si lenjeriei de corp)'),
('1393','Fabricarea de covoare si mochete'),
('1394','Fabricarea de odgoane, franghii, sfori si plase'),
('1395','Fabricarea de textile netesute si articole din acestea, cu excepția confectiilor de imbracaminte'),
('1396','Fabricarea de articole tehnice si industriale din textile'),
('1399','Fabricarea altor articole textile n.c.a.'),
('14','Fabricarea articolelor de îmbrăcăminte'),
('141','Fabricarea articolelor de imbracaminte, cu excepția articolelor din blana'),
('1411','Fabricarea articolelor de imbracaminte din piele'),
('1412','Fabricarea de articole de imbracaminte pentru lucru'),
('1413','Fabricarea altor articole de imbracaminte (exclusiv lenjeria de corp)'),
('1414','Fabricarea de articole de lenjerie de corp'),
('1419','Fabricarea altor articole de imbracaminte si accesorii n.c.a.'),
('142','Fabricarea articolelor din blana'),
('1420','Fabricarea articolelor din blana'),
('143','Fabricarea articolelor de imbracaminte prin tricotare sau crosetare'),
('1431','Fabricarea prin tricotare sau crosetare a ciorapilor si articolelor de galanterie'),
('1439','Fabricarea prin tricotare sau crosetare a altor articole de imbracaminte'),
('15','Tăbăcirea și finisarea pieilor; fabricarea articolelor de voiaj și marochinărie, harnașamentelor și încălțămintei; prepararea și vopsirea blănurilor'),
('151','Tăbăcirea si finisarea pieilor; fabricarea articolelor de voiaj si marochinarie si a articolelor de harnasament; prepararea si vopsirea blanurilor'),
('1511','Tăbăcirea si finisarea pieilor; prepararea si vopsirea blanurilor'),
('1512','Fabricarea articolelor de voiaj si marochinarie si a articolelor de harnasament'),
('152','Fabricarea incaltamintei'),
('1520','Fabricarea incaltamintei'),
('16','Prelucrarea lemnului, fabricarea produselor din lemn și plută, cu excepția mobilei; fabricarea articolelor din paie și din alte materiale vegetale împletite'),
('161','Tăierea si rindeluirea lemnului'),
('1610','Tăierea si rindeluirea lemnului'),
('162','Fabricarea produselor din lemn, pluta, paie si din alte materiale vegetale'),
('1621','Fabricarea de furnire si a panourilor de lemn'),
('1622','Fabricarea parchetului asamblat in panouri'),
('1623','Fabricarea altor elemente de dulgherie si tamplarie, pentru construcții'),
('1624','Fabricarea ambalajelor din lemn'),
('1629','Fabricarea altor produse din lemn; fabricarea articolelor din pluta, paie si din alte materiale vegetale impletite'),
('17','Fabricarea hârtiei și a produselor din hârtie'),
('171','Fabricarea celulozei, hârtiei si cartonului'),
('1711','Fabricarea celulozei'),
('1712','Fabricarea hârtiei si cartonului'),
('172','Fabricarea articolelor din hârtie și carton'),
('1721','Fabricarea hârtiei si cartonului ondulat si a ambalajelor din hartie si carton'),
('1722','Fabricarea produselor de uz gospodaresc si sanitar, din hartie sau carton'),
('1723','Fabricarea articolelor de papetarie'),
('1724','Fabricarea tapetului'),
('1729','Fabricarea altor articole din hârtie și carton n.c.a'),
('18','Tipărire și reproducerea pe suporți a înregistrărilor'),
('181','Alte activități de tiparire n.c.a.'),
('1811','Tiparirea ziarelor'),
('1812','Alte activități de tiparire n.c.a.'),
('1813','Servicii pregatitoare pentru pretiparire'),
('1814','Legatorie si servicii conexe'),
('182','Reproducerea inregistrarilor'),
('1820','Reproducerea inregistrarilor'),
('19','Fabricarea produselor de cocserie și a produselor obținute din prelucrarea țițeiului'),
('191','Fabricarea produselor de cocserie'),
('1910','Fabricarea produselor de cocserie'),
('192','Fabricarea produselor obținute din prelucrarea titeiului'),
('1920','Fabricarea produselor obținute din prelucrarea titeiului'),
('20','Fabricarea substanțelor și a produselor chimice'),
('201','Fabricarea produselor chimice de baza, a ingrasamintelor si produselor azotoase; fabricarea materialelor plastice si a cauciucului sintetic, in forme primare'),
('2011','Fabricarea gazelor industriale'),
('2012','Fabricarea colorantilor si a pigmentilor'),
('2013','Fabricarea altor produse chimice anorganice, de baza'),
('2014','Fabricarea altor produse chimice organice, de baza'),
('2015','Fabricarea ingrasamintelor si produselor azotoase'),
('2016','Fabricarea materialelor plastice in forme primare'),
('2017','Fabricarea cauciucului sintetic in forme primare'),
('202','Fabricarea pesticidelor si a altor produse agrochimice'),
('2020','Fabricarea pesticidelor si a altor produse agrochimice'),
('203','Fabricarea vopselelor, lacurilor, cernelii tipografice si masticurilor'),
('2030','Fabricarea vopselelor, lacurilor, cernelii tipografice si masticurilor'),
('204','Fabricarea sapunurilor, detergentilor si a produselor de intretinere, cosmetice si de parfumerie'),
('2041','Fabricarea sapunurilor, detergentilor si a produselor de intretinere'),
('2042','Fabricarea parfumurilor si a produselor cosmetice (de toaleta)'),
('205','Fabricarea altor produse chimice'),
('2051','Fabricarea explozivilor'),
('2052','Fabricarea cleiurilor'),
('2053','Fabricarea uleiurilor esentiale'),
('2059','Fabricarea altor produse chimice n.c.a.'),
('206','Fabricarea fibrelor sintetice si artificiale'),
('2060','Fabricarea fibrelor sintetice si artificiale'),
('21','Fabricarea produselor farmaceutice de bază și a preparatelor farmaceutice'),
('211','Fabricarea produselor farmaceutice de baza'),
('2110','Fabricarea produselor farmaceutice de baza'),
('212','Fabricarea preparatelor farmaceutice'),
('2120','Fabricarea preparatelor farmaceutice'),
('22','Fabricarea produselor din cauciuc și mase plastice'),
('221','Fabricarea articolelor din cauciuc'),
('2211','Fabricarea anvelopelor si a camerelor de aer; reșaparea si refacerea anvelopelor'),
('2219','Fabricarea altor produse din cauciuc'),
('222','Fabricarea articolelor de ambalaj din material plastic'),
('2221','Fabricarea placilor, foliilor, tuburilor si profilelor din material plastic'),
('2222','Fabricarea articolelor de ambalaj din material plastic'),
('2223','Fabricarea articolelor din material plastic pentru construcții'),
('2229','Fabricarea altor produse din material plastic'),
('23','Fabricarea altor produse din minerale nemetalice'),
('231','Fabricarea sticlei si a articolelor din sticla'),
('2311','Fabricarea sticlei plate'),
('2312','Prelucrarea si fasonarea sticlei plate'),
('2313','Fabricarea articolelor din sticla'),
('2314','Fabricarea fibrelor din sticla'),
('2319','Fabricarea de sticlarie tehnica'),
('232','Fabricarea de produse refractare'),
('2320','Fabricarea de produse refractare'),
('233','Fabricarea materialelor de construcții din argila'),
('2331','Fabricarea placilor si dalelor din ceramica'),
('2332','Fabricarea cărămizilor, tiglelor si a altor produse pentru construcții, din argila arsa'),
('234','Fabricarea altor articole din ceramica si portelan'),
('2341','Fabricarea articolelor ceramice pentru uz gospodaresc si ornamental'),
('2342','Fabricarea de obiecte sanitare din ceramica'),
('2343','Fabricarea izolatorilor si pieselor izolante din ceramica'),
('2344','Fabricarea altor produse tehnice din ceramica'),
('2349','Fabricarea altor produse ceramice n.c.a.'),
('235','Fabricarea cimentului, varului si ipsosului'),
('2351','Fabricarea cimentului'),
('2352','Fabricarea varului si ipsosului'),
('236','Fabricarea articolelor din beton, ciment si ipsos'),
('2361','Fabricarea produselor din beton pentru construcții'),
('2362','Fabricarea produselor din ipsos pentru construcții'),
('2363','Fabricarea betonului'),
('2364','Fabricarea mortarului'),
('2365','Fabricarea produselor din azbociment'),
('2369','Fabricarea altor articole din beton, ciment si ipsos'),
('237','Tăierea, fasonarea si finisarea pietrei'),
('2370','Tăierea, fasonarea si finisarea pietrei'),
('239','Fabricarea produselor abrazive si a altor produse din minerale nemetalice n.c.a.'),
('2391','Fabricarea de produse abrazive'),
('2399','Fabricarea altor produse din minerale nemetalice, n.c.a.'),
('24','Industria metalurgică'),
('241','Producția de metale feroase sub forme primare si de feroaliaje'),
('2410','Producția de metale feroase sub forme primare si de feroaliaje'),
('242','Producția de tuburi, tevi, profile tubulare si accesorii pentru acestea, din otel'),
('2420','Producția de tuburi, tevi, profile tubulare si accesorii pentru acestea, din otel'),
('243','Producția de profile obținute la rece'),
('2431','Tragere la rece a barelor'),
('2432','Laminare la rece a benzilor inguste'),
('2433','Producția de profile obținute la rece'),
('2434','Trefilarea firelor la rece'),
('244','Producția metalelor pretioase si a altor metale neferoase'),
('2441','Producția metalelor pretioase'),
('2442','Metalurgia aluminiului'),
('2443','Producția plumbului, zincului si cositorului'),
('2444','Metalurgia cuprului'),
('2445','Producția altor metale neferoase'),
('2446','Prelucrarea combustibililor nucleari'),
('245','Turnarea metalelor'),
('2451','Turnarea fontei'),
('2452','Turnarea otelului'),
('2453','Turnarea metalelor neferoase usoare'),
('2454','Turnarea altor metale neferoase'),
('25','Industria construcțiilor metalice și a produselor din metal, exclusiv mașini, utilaje și instalații'),
('251','Fabricarea de construcții metalice'),
('2511','Fabricarea de construcții metalice si parti componente ale structurilor metalice'),
('2512','Fabricarea de usi si ferestre din metal'),
('252','Producția de rezervoare, cisterne si containere metalice; producția de radiatoare si cazane pentru incalzire centrala'),
('2521','Producția de radiatoare si cazane pentru incalzire centrala'),
('2529','Producția de rezervoare, cisterne si containere metalice'),
('253','Producția generatoarelor de aburi (cu excepția cazanelor pentru incalzire centrala)'),
('2530','Producția generatoarelor de aburi (cu excepția cazanelor pentru incalzire centrala)'),
('254','Fabricarea armamentului si muniției'),
('2540','Fabricarea armamentului si muniției'),
('255','Fabricarea produselor metalice obținute prin deformare plastica; metalurgia pulberilor'),
('2550','Fabricarea produselor metalice obținute prin deformare plastica; metalurgia pulberilor'),
('256','Tratarea si acoperirea metalelor; operatiuni de mecanica generala pe baza de plata sau contract'),
('2561','Tratarea si acoperirea metalelor'),
('2562','Operatiuni de mecanica generala'),
('257','Producția de unelte si articole de fierarie'),
('2571','Fabricarea produselor de taiat'),
('2572','Fabricarea articolelor de feronerie'),
('2573','Fabricarea uneltelor'),
('259','Fabricarea altor produse prelucrate din metal'),
('2591','Fabricarea de recipienti, containere si alte produse similare din otel'),
('2592','Fabricarea ambalajelor usoare din metal'),
('2593','Fabricarea articolelor din fire metalice; fabricarea de lanturi si arcuri'),
('2594','Fabricarea de suruburi, buloane si alte articole filetate; fabricarea de nituri si saibe'),
('2599','Fabricarea altor articole din metal n.c.a.'),
('26','Fabricarea calculatoarelor și a produselor electronice și optice'),
('261','Fabricarea componentelor electronice'),
('2611','Fabricarea subansamblurilor electronice (module)'),
('2612','Fabricarea altor componente electronice'),
('262','Fabricarea calculatoarelor si a echipamentelor periferice'),
('2620','Fabricarea calculatoarelor si a echipamentelor periferice'),
('263','Fabricarea echipamentelor de comunicații'),
('2630','Fabricarea echipamentelor de comunicații'),
('264','Fabricarea produselor electronice de larg consum'),
('2640','Fabricarea produselor electronice de larg consum'),
('265','Fabricarea de echipamente de masura, verificare, control si navigație; producția de ceasuri'),
('2651','Fabricarea de instrumente si dispozitive pentru masura, verificare, control, navigație'),
('2652','Producția de ceasuri'),
('266','Fabricarea de echipamente pentru radiologie, electrodiagnostic si electroterapie'),
('2660','Fabricarea de echipamente pentru radiologie, electrodiagnostic si electroterapie'),
('267','Fabricarea de instrumente optice si echipamente fotografice'),
('2670','Fabricarea de instrumente optice si echipamente fotografice'),
('268','Fabricarea suporților magnetici si optici destinați inregistrarilor'),
('2680','Fabricarea suporților magnetici si optici destinați inregistrarilor'),
('27','Fabricarea echipamentelor electrice'),
('271','Fabricarea motoarelor electrice, generatoarelor si transformatoarelor electrice si a aparatelor de distributie si control a electricitatii'),
('2711','Fabricarea motoarelor, generatoarelor si transformatoarelor electrice'),
('2712','Fabricarea aparatelor de distributie si control a electricitatii'),
('272','Fabricarea de acumulatori si baterii'),
('2720','Fabricarea de acumulatori si baterii'),
('273','Fabricarea de fire si cabluri; fabricarea dispozitivelor de conexiune pentru acestea'),
('2731','Fabricarea de cabluri cu fibra optica'),
('2732','Fabricarea altor fire si cabluri electrice si electronice'),
('2733','Fabricarea dispozitivelor de conexiune pentru fire si cabluri electrice si electronice'),
('274','Fabricarea de echipamente electrice de iluminat'),
('2740','Fabricarea de echipamente electrice de iluminat'),
('275','Fabricarea de echipamente casnice'),
('2751','Fabricarea de aparate electrocasnice'),
('2752','Fabricarea de echipamente casnice neelectrice'),
('279','Fabricarea altor echipamente electrice'),
('2790','Fabricarea altor echipamente electrice'),
('28','Fabricarea de mașini, utilaje și echipamente n.c.a.'),
('281','Fabricarea de masini si utilaje de utilizare generala'),
('2811','Fabricarea de motoare si turbine (cu excepția celor pentru avioane, autovehicule si motociclete)'),
('2812','Fabricarea de motoare hidraulice'),
('2813','Fabricarea de pompe si compresoare'),
('2814','Fabricarea de articole de robinetarie'),
('2815','Fabricarea lagarelor, angrenajelor, cutiilor de viteza si a elementelor mecanice de transmisie'),
('282','Fabricarea altor masini si utilaje de utilizare generala'),
('2821','Fabricarea cuptoarelor, furnalelor si arzatoarelor'),
('2822','Fabricarea echipamentelor de ridicat si manipulat'),
('2823','Fabricarea mașinilor si echipamentelor de birou (exclusiv fabricarea calculatoarelor si a echipamentelor periferice)'),
('2824','Fabricarea mașinilor-unelte portabile actionate electric'),
('2825','Fabricarea echipamentelor de ventilatie si frigorifice, exclusiv a echipamentelor de uz casnic'),
('2829','Fabricarea altor masini si utilaje de utilizare generala n.c.a.'),
('283','Fabricarea mașinilor si utilajelor pentru agricultura si exploatari forestiere'),
('2830','Fabricarea mașinilor si utilajelor pentru agricultura si exploatari forestiere'),
('284','Fabricarea utilajelor pentru prelucrarea metalului si a mașinilor-unelte'),
('2841','Fabricarea utilajelor si a mașinilor-unelte pentru prelucrarea metalului'),
('2849','Fabricarea altor masini-unelte n.c.a.'),
('289','Fabricarea utilajelor pentru industria textila, a imbracamintei si a pielariei'),
('2891','Fabricarea utilajelor pentru metalurgie'),
('2892','Fabricarea utilajelor pentru extracție si construcții'),
('2893','Fabricarea utilajelor pentru prelucrarea produselor alimentare, băuturilor si tutunului'),
('2894','Fabricarea utilajelor pentru industria textila, a imbracamintei si a pielariei'),
('2895','Fabricarea utilajelor pentru industria hârtiei si cartonului'),
('2896','Fabricarea utilajelor pentru prelucrarea maselor plastice si a cauciucului'),
('2899','Fabricarea altor masini si utilaje specifice n.c.a.'),
('29','Fabricarea autovehiculelor de transport rutier, a remorcilor și semiremorcilor'),
('291','Fabricarea autovehiculelor de transport rutier'),
('2910','Fabricarea autovehiculelor de transport rutier'),
('292','Producția de caroserii pentru autovehicule; fabricarea de remorci si semiremorci'),
('2920','Producția de caroserii pentru autovehicule; fabricarea de remorci si semiremorci'),
('293','Producția de piese si accesorii pentru autovehicule si pentru motoare de autovehicule'),
('2931','Fabricarea de echipamente electrice si electronice pentru autovehicule si pentru motoare de autovehicule'),
('2932','Fabricarea altor piese si accesorii pentru autovehicule si pentru motoare de autovehicule'),
('30','Fabricarea altor mijloace de transport'),
('301','Construcția de nave si bărci'),
('3011','Construcția de nave si structuri plutitoare'),
('3012','Construcția de ambarcatiuni sportive si de agrement'),
('302','Fabricarea materialului rulant'),
('3020','Fabricarea materialului rulant'),
('303','Fabricarea de aeronave si nave spatiale'),
('3030','Fabricarea de aeronave si nave spatiale'),
('304','Fabricarea vehiculelor militare de lupta'),
('3040','Fabricarea vehiculelor militare de lupta'),
('309','Fabricarea altor echipamente de transport n.c.a.'),
('3091','Fabricarea de motociclete'),
('3092','Fabricarea de biciclete si de vehicule pentru invalizi'),
('3099','Fabricarea altor mijloace de transport n.c.a.'),
('31','Fabricarea de mobilă'),
('310','Fabricarea de mobila'),
('3101','Fabricarea de mobila pentru birouri si magazine'),
('3102','Fabricarea de mobila pentru bucatarii'),
('3103','Fabricarea de saltele si somiere'),
('3109','Fabricarea de mobila n.c.a.'),
('32','Alte activități industriale n.c.a'),
('321','Fabricarea bijuteriilor, imitatiilor de bijuterii si articolelor similare'),
('3211','Baterea monedelor'),
('3212','Fabricarea bijuteriilor si articolelor similare din metale si pietre pretioase'),
('3213','Fabricarea imitatiilor de bijuterii si articole similare'),
('322','Fabricarea instrumentelor muzicale'),
('3220','Fabricarea instrumentelor muzicale'),
('323','Fabricarea articolelor pentru sport'),
('3230','Fabricarea articolelor pentru sport'),
('324','Fabricarea jocurilor si jucariilor'),
('3240','Fabricarea jocurilor si jucariilor'),
('325','Fabricarea de dispozitive, aparate si instrumente medicale si stomatologice'),
('3250','Fabricarea de dispozitive, aparate si instrumente medicale si stomatologice'),
('329','Alte activități industriale'),
('3291','Fabricarea maturilor si periilor'),
('3299','Fabricarea altor produse manufacturiere n.c.a.'),
('33','Repararea, întreținerea și instalarea mașinilor și echipamentelor'),
('331','Repararea articolelor fabricate din metal, repararea mașinilor si echipamentelor'),
('3311','Repararea articolelor fabricate din metal'),
('3312','Repararea mașinilor'),
('3313','Repararea echipamentelor electronice si optice'),
('3314','Repararea echipamentelor electrice'),
('3315','Repararea si intretinerea navelor si bărcilor'),
('3316','Repararea si intretinerea aeronavelor si navelor spatiale'),
('3317','Repararea si intretinerea altor echipamente de transport n.c.a.'),
('3319','Repararea altor echipamente'),
('332','Instalarea mașinilor si echipamentelor industriale'),
('3320','Instalarea mașinilor si echipamentelor industriale'),
('D','Producția și furnizarea de energie electrică și termică, gaze, apă caldă și aer condiționat'),
('35','Producția și furnizarea de energie electrică și termică, gaze, apă caldă și aer condiționat'),
('351','Producția, transportul si distributia energiei electrice'),
('3511','Producția de energie electrica'),
('3512','Transportul energiei electrice'),
('3513','Distributia energiei electrice'),
('3514','Comercializarea energiei electrice'),
('352','Producția gazelor; distributia combustibililor gazosi prin conducte'),
('3521','Producția gazelor'),
('3522','Distributia combustibililor gazosi, prin conducte'),
('3523','Comercializarea combustibililor gazosi, prin conducte'),
('353','Furnizarea de abur si aer conditionat'),
('3530','Furnizarea de abur si aer conditionat'),
('E','Distribuția apei; salubritate, gestionarea deșeurilor, activități de decontaminare'),
('36','Captarea, tratarea și distribuția apei'),
('360','Captarea, tratarea si distributia apei'),
('3600','Captarea, tratarea si distributia apei'),
('37','Colectarea și epurarea apelor uzate'),
('370','Colectarea si epurarea apelor uzate'),
('3700','Colectarea si epurarea apelor uzate'),
('38','Colectarea, tratarea și eliminarea deșeurilor; activități de recuperare a materialelor reciclabile'),
('381','Colectarea deseurilor'),
('3811','Colectarea deseurilor nepericuloase'),
('3812','Colectarea deseurilor periculoase'),
('382','Tratarea si eliminarea deseurilor'),
('3821','Tratarea si eliminarea deseurilor nepericuloase'),
('3822','Tratarea si eliminarea deseurilor periculoase'),
('383','Recuperare materialelor'),
('3831','Demontarea (dezasamblarea) mașinilor si echipamentelor scoase din uz pentru recuperarea materialelor'),
('3832','Recuperarea materialelor reciclabile sortate'),
('39','Activități și servicii de decontaminare'),
('390','Activități si servicii de decontaminare'),
('3900','Activități si servicii de decontaminare'),
('F','Construcții'),
('41','Construcții de clădiri'),
('411','Dezvoltare (promovare) imobiliara'),
('4110','Dezvoltare (promovare) imobiliara'),
('412','Lucrari de construcții a cladirilor rezidentiale si nerezidentiale'),
('4120','Lucrari de construcții a cladirilor rezidentiale si nerezidentiale'),
('42','Lucrări de geniu civil'),
('421','Lucrari de construcții a drumurilor si a cailor ferate'),
('4211','Lucrari de construcții a drumurilor si autostrazilor'),
('4212','Lucrari de construcții a cailor ferate de suprafata si subterane'),
('4213','Construcția de poduri si tuneluri'),
('422','Lucrari de construcții a proiectelor utilitare'),
('4221','Lucrari de construcții a proiectelor utilitare pentru fluide'),
('4222','Lucrari de construcții a proiectelor utilitare pentru electricitate si telecomunicații'),
('429','Lucrari de construcții a altor proiecte ingineresti'),
('4291','Construcții hidrotehnice'),
('4299','Lucrari de construcții a altor proiecte ingineresti n.c.a'),
('43','Lucrări speciale de construcții'),
('431','Lucrari de demolare si de pregatire a terenului'),
('4311','Lucrari de demolare a construcțiilor'),
('4312','Lucrari de pregatire a terenului'),
('4313','Lucrari de foraj si sondaj pentru construcții'),
('432','Lucrari de instalatii electrice si tehnico-sanitare si alte lucrari de instalatii pentru construcții'),
('4321','Lucrari de instalatii electrice'),
('4322','Lucrari de instalatii sanitare, de incalzire si de aer conditionat'),
('4329','Alte lucrari de instalatii pentru construcții'),
('433','Lucrari de finisare'),
('4331','Lucrari de ipsoserie'),
('4332','Lucrari de tamplarie si dulgherie'),
('4333','Lucrari de pardosire si placare a peretilor'),
('4334','Lucrari de vopsitorie, zugraveli si montari de geamuri'),
('4339','Alte lucrari de finisare'),
('439','Alte lucrari speciale de construcții'),
('4391','Lucrari de invelitori, sarpante si terase la construcții'),
('4399','Alte lucrari speciale de construcții n.c.a.'),
('G','Comerț cu ridicata și cu amănuntul; repararea autovehiculelor și motocicletelor'),
('45','Comerț cu ridicata și cu amănuntul, întreținerea și repararea autovehiculelor și a motocicletelor'),
('451','Comerț cu autovehicule'),
('4511','Comerț cu autoturisme si autovehicule usoare (sub 3,5 tone)'),
('4519','Comerț cu alte autovehicule'),
('452','Intretinerea si repararea autovehiculelor'),
('4520','Intretinerea si repararea autovehiculelor'),
('453','Comerț cu piese si accesorii pentru autovehicule'),
('4531','Comerț cu ridicata de piese si accesorii pentru autovehicule'),
('4532','Comerț cu amănuntul de piese si accesorii pentru autovehicule'),
('454','Comerț cu motociclete, piese si accesorii aferente; intretinerea si repararea motocicletelor'),
('4540','Comerț cu motociclete, piese si accesorii aferente; intretinerea si repararea motocicletelor'),
('46','Comerț cu ridicata cu excepția comerțului cu autovehicule și motociclete'),
('461','Activitați de intermediere în comerțul cu ridicata'),
('4611','Intermedieri in comerțul cu materii prime agricole, animale vii, materii prime textile si cu semifabricate'),
('4612','Intermedieri in comerțul cu combustibili, minereuri, metale si produse chimice pentru industrie'),
('4613','Intermedieri in comerțul cu material lemnos si materiale de construcții'),
('4614','Intermedieri in comerțul cu masini, echipamente industriale, nave si avioane'),
('4615','Intermedieri in comerțul cu mobila, articole de menaj si de fierarie'),
('4616','Intermedieri in comerțul cu textile, confectii din blana, incaltaminte si articole din piele'),
('4617','Intermedieri in comerțul cu produse alimentare, bauturi si tutun'),
('4618','Intermedieri in comerțul specializat in vânzarea produselor cu caracter specific, n.c.a.'),
('4619','Intermedieri in comerțul cu produse diverse'),
('462','Comerț cu ridicata al produselor agricole brute si al animalelor vii'),
('4621','Comerț cu ridicata al cerealelor, semințelor, furajelor si tutunului neprelucrat'),
('4622','Comerț cu ridicata al florilor si al plantelor'),
('4623','Comerț cu ridicata al animalelor vii'),
('4624','Comerț cu ridicata al blanurilor, pieilor brute si al pieilor prelucrate'),
('463','Comerț cu ridicata al produselor alimentare, al băuturilor si al tutunului'),
('4631','Comerț cu ridicata al fructelor si legumelor'),
('4632','Comerț cu ridicata al carnii si produselor din carne'),
('4633','Comerț cu ridicata al produselor lactate, oualor, uleiurilor si grasimilor comestibile'),
('4634','Comerț cu ridicata al băuturilor'),
('4635','Comerț cu ridicata al produselor din tutun'),
('4636','Comerț cu ridicata al zaharului, ciocolatei si produselor zaharoase'),
('4637','Comerț cu ridicata cu cafea, ceai, cacao si condimente'),
('4638','Comerț cu ridicata specializat al altor alimente, inclusiv peste, crustacee si moluste'),
('4639','Comerț cu ridicata nespecializat de produse alimentare, bauturi si tutun'),
('464','Comerț cu ridicata al bunurilor de consum'),
('4641','Comerț cu ridicata al produselor textile'),
('4642','Comerț cu ridicata al imbracamintei si incaltamintei'),
('4643','Comerț cu ridicata al aparatelor electrice de uz gospodaresc, al aparatelor de radio si televizoarelor'),
('4644','Comerț cu ridicata al produselor din ceramica, sticlarie, si produse de intretinere'),
('4645','Comerț cu ridicata al produselor cosmetice si de parfumerie'),
('4646','Comerț cu ridicata al produselor farmaceutice'),
('4647','Comerț cu ridicata al mobilei, covoarelor si a articolelor de iluminat'),
('4648','Comerț cu ridicata al ceasurilor si bijuteriilor'),
('4649','Comerț cu ridicata al altor bunuri de uz gospodaresc'),
('465','Comerț cu ridicata al echipamentului informatic si de telecomunicații'),
('4651','Comerț cu ridicata al calculatoarelor, echipamentelor periferice si software- ului'),
('4652','Comerț cu ridicata de componente si echipamente electronice si de telecomunicații'),
('466','Comerț cu ridicata al altor masini, echipamente si furnituri'),
('4661','Comerț cu ridicata al mașinilor agricole, echipamentelor si furniturilor'),
('4662','Comerț cu ridicata al mașinilor- unelte'),
('4663','Comerț cu ridicata al mașinilor pentru industria miniera si construcții'),
('4664','Comerț cu ridicata al mașinilor pentru industria textila si al mașinilor de cusut si de tricotat'),
('4665','Comerț cu ridicata al mobilei de birou'),
('4666','Comerț cu ridicata al altor masini si echipamente de birou'),
('4669','Comerț cu ridicata al altor masini si echipamente'),
('467','Comerț cu ridicata specializat al altor produse'),
('4671','Comerț cu ridicata al combustibililor solizi, lichizi si gazosi si al produselor derivate'),
('4672','Comerț cu ridicata al metalelor si minereurilor metalice'),
('4673','Comerț cu ridicata al materialului lemnos si al materialelor de construcții si echipamentelor sanitare'),
('4674','Comerț cu ridicata al echipamentelor si furniturilor de fierarie pentru instalatii sanitare si de incalzire'),
('4675','Comerț cu ridicata al produselor chimice'),
('4676','Comerț cu ridicata al altor produse intermediare'),
('4677','Comerț cu ridicata al deseurilor si resturilor'),
('469','Comerț cu ridicata nespecializat'),
('4690','Comerț cu ridicata nespecializat'),
('47','Comerț cu amănuntul, cu excepția autovehiculelor și motocicletelor'),
('471','Comerț cu amănuntul in magazine nespecializate'),
('4711','Comerț cu amănuntul in magazine nespecializate, cu vânzare predominanta de produse alimentare, bauturi si tutun'),
('4719','Comerț cu amănuntul in magazine nespecializate, cu vânzare predominanta de produse nealimentare'),
('472','Comerț cu amănuntul al produselor alimentare, băuturilor si al produselor din tutun, in magazine specializate'),
('4721','Comerț cu amănuntul al fructelor si legumelor proaspete, in magazine specializate'),
('4722','Comerț cu amănuntul al carnii si al produselor din carne, in magazine specializate'),
('4723','Comerț cu amănuntul al pestelui, crustaceelor si molustelor, in magazine specializate'),
('4724','Comerț cu amănuntul al painii, produselor de patiserie si produselor zaharoase, in magazine specializate'),
('4725','Comerț cu amănuntul al băuturilor, in magazine specializate'),
('4726','Comerț cu amănuntul al produselor din tutun, in magazine specializate'),
('4729','Comerț cu amănuntul al altor produse alimentare, in magazine specializate'),
('473','Comerț cu amănuntul al carburantilor pentru autovehicule in magazine specializate'),
('4730','Comerț cu amănuntul al carburantilor pentru autovehicule in magazine specializate'),
('474','Comerț cu amănuntul al echipamentului informatic si de telecomunicații in magazine specializate'),
('4741','Comerț cu amănuntul al calculatoarelor, unitatilor periferice si software-ului in magazine specializate'),
('4742','Comerț cu amănuntul al echipamentului pentru telecomunicații in magazine specializate'),
('4743','Comerț cu amănuntul al echipamentului audio/video in magazine specializate'),
('475','Comerț cu amănuntul al altor produse casnice, in magazine specializate'),
('4751','Comerț cu amănuntul al textilelor, in magazine specializate'),
('4752','Comerț cu amănuntul al articolelor de fierarie, al articolelor din sticla si a celor pentru vopsit, in magazine specializate'),
('4753','Comerț cu amănuntul al covoarelor, carpetelor, tapetelor si a altor acoperitoare de podea, in magazine specializate'),
('4754','Comerț cu amănuntul al articolelor si aparatelor electrocasnice, in magazine specializate'),
('4759','Comerț cu amănuntul al mobilei, al articolelor de iluminat si al articolelor de uz casnic n.c.a., in magazine specializate'),
('476','Comerț cu amănuntul de bunuri culturale si recreative, in magazine specializate'),
('4761','Comerț cu amănuntul al cartilor, in magazine specializate'),
('4762','Comerț cu amănuntul al ziarelor si articolelor de papetarie, in magazine specializate'),
('4763','Comerț cu amănuntul al discurilor si benzilor magnetice cu sau fără inregistrari audio/video , in magazine specializate'),
('4764','Comerț cu amănuntul al echipamentelor sportive, in magazine specializate'),
('4765','Comerț cu amănuntul al jocurilor si jucariilor, in magazine specializate'),
('477','Comerț cu amănuntul al altor bunuri, în magazine specializate'),
('4771','Comerț cu amănuntul al imbracamintei, in magazine specializate'),
('4772','Comerț cu amănuntul al incaltamintei si articolelor din piele, in magazine specializate'),
('4773','Comerț cu amănuntul al produselor farmaceutice, in magazine specializate'),
('4774','Comerț cu amănuntul al articolelor medicale si ortopedice, in magazine specializate'),
('4775','Comerț cu amănuntul al produselor cosmetice si de parfumerie, in magazine specializate'),
('4776','Comerț cu amănuntul al florilor, plantelor si semințelor, comerț cu amănuntul al animalelor de companie si a hranei pentru acestea, in magazine specializate'),
('4777','Comerț cu amănuntul al ceasurilor si bijuteriilor, in magazine specializate'),
('4778','Comerț cu amănuntul al altor bunuri noi, in magazine specializate'),
('4779','Comerț cu amănuntul al bunurilor de ocazie vandute prin magazine'),
('478','Comerț cu amănuntul efectuat prin standuri, chioșcuri si piete'),
('4781','Comerț cu amănuntul al produselor alimentare, băuturilor si produselor din tutun efectuat prin standuri, chioșcuri si piete'),
('4782','Comerț cu amănuntul al textilelor, imbracamintei si incaltamintei efectuat prin standuri, chioșcuri si piete'),
('4789','Comerț cu amănuntul prin standuri, chioșcuri si piete al altor produse'),
('479','Comerț cu amănuntul care nu se efectueaza prin magazine, standuri, chioșcuri si piete'),
('4791','Comerț cu amănuntul prin intermediul caselor de comenzi sau prin Internet'),
('4799','Comerț cu amănuntul efectuat in afara magazinelor, standurilor, chioșcurilor si piețelor'),
('H','Transport și depozitare'),
('49','Transporturi terestre și transporturi prin conducte'),
('491','Transporturi interurbane de călători pe calea ferata'),
('4910','Transporturi interurbane de călători pe calea ferata'),
('492','Transporturi de marfa pe calea ferata'),
('4920','Transporturi de marfa pe calea ferata'),
('493','Alte transporturi terestre de călători'),
('4931','Transporturi urbane, suburbane si metropolitane de călători'),
('4932','Transporturi cu taxiuri'),
('4939','Alte transporturi terestre de călători n.c.a'),
('494','Transporturi rutiere de marfuri si servicii de mutare'),
('4941','Transporturi rutiere de marfuri'),
('4942','Servicii de mutare'),
('495','Transporturi prin conducte'),
('4950','Transporturi prin conducte'),
('50','Transporturi pe apă'),
('501','Transporturi maritime si costiere de pasageri'),
('5010','Transporturi maritime si costiere de pasageri'),
('502','Transporturi maritime si costiere de marfa'),
('5020','Transporturi maritime si costiere de marfa'),
('503','Transporturi de pasageri pe cai navigabile interioare'),
('5030','Transporturi de pasageri pe cai navigabile interioare'),
('504','Transportul de marfa pe cai navigabile interioare'),
('5040','Transportul de marfa pe cai navigabile interioare'),
('51','Transporturi aeriene'),
('511','Transporturi aeriene de pasageri'),
('5110','Transporturi aeriene de pasageri'),
('512','Transporturi aeriene de marfa si transporturi spatiale'),
('5121','Transporturi aeriene de marfa'),
('5122','Transporturi spatiale'),
('52','Depozitare și activități auxiliare pentru transporturi'),
('521','Depozitări'),
('5210','Depozitări'),
('522','Activități anexe pentru transporturi'),
('5221','Activități de servicii anexe pentru transporturi terestre'),
('5222','Activități de servicii anexe transportului pe apa'),
('5223','Activități de servicii anexe transporturilor aeriene'),
('5224','Manipulari'),
('5229','Alte activități anexe transporturilor'),
('53','Activități de poștă și de curier'),
('531','Activități poștale desfășurate sub obligativitatea serviciului universal'),
('5310','Activități poștale desfășurate sub obligativitatea serviciului universal'),
('532','Alte activități poștale si de curier'),
('5320','Alte activități poștale si de curier'),
('I','Hoteluri și restaurante'),
('55','Hoteluri și alte facilități de cazare'),
('551','Hoteluri si alte facilități de cazare similare'),
('5510','Hoteluri si alte facilități de cazare similare'),
('552','Facilități de cazare pentru vacante si perioade de scurta durata'),
('5520','Facilități de cazare pentru vacante si perioade de scurta durata'),
('553','Parcuri pentru rulote, campinguri si tabere'),
('5530','Parcuri pentru rulote, campinguri si tabere'),
('559','Alte servicii de cazare'),
('5590','Alte servicii de cazare'),
('56','Restaurante și alte activități de servicii de alimentație'),
('561','Restaurante'),
('5610','Restaurante'),
('562','Activități de alimentatie (catering) pentru evenimente si alte servicii de alimentatie'),
('5621','Activități de alimentatie (catering) pentru evenimente'),
('5629','Alte servicii de alimentatie n.c.a.'),
('563','Baruri si alte activități de servire a băuturilor'),
('5630','Baruri si alte activități de servire a băuturilor'),
('J','Informații și comunicații'),
('58','Activități de editare'),
('581','Activități de editare a cartilor, ziarelor, revistelor si alte activități de editare'),
('5811','Activități de editare a cartilor'),
('5812','Activități de editare de ghiduri, compendii, liste de adrese si similare'),
('5813','Activități de editare a ziarelor'),
('5814','Activități de editare a revistelor si periodicelor'),
('5819','Alte activități de editare'),
('582','Activități de editare a produselor software'),
('5821','Activități de editare a jocurilor de calculator'),
('5829','Activități de editare a altor produse software'),
('59','Activități de producție cinematografică, video și de programe de televiziune; înregistrări audio și activități de editare muzicală'),
('591','Activități de productie cinematografica, video si de programe de televiziune'),
('5911','Activități de productie cinematografica, video si de programe de televiziune'),
('5912','Activități de post-productie cinematografica, video si de programe de televiziune'),
('5913','Activități de distributie a filmelor cinematografice, video si a programelor de televiziune'),
('5914','Proiectia de filme cinematografice'),
('592','Activități de realizare a inregistrarilor audio si activități de editare muzicala'),
('5920','Activități de realizare a inregistrarilor audio si activități de editare muzicala'),
('60','Activități de difuzare și transmitere de programe'),
('601','Activități de difuzare a programelor de radio'),
('6010','Activități de difuzare a programelor de radio'),
('602','Activități de difuzare a programelor de televiziune'),
('6020','Activități de difuzare a programelor de televiziune'),
('61','Telecomunicații'),
('611','Activități de telecomunicații prin retele cu cablu'),
('6110','Activități de telecomunicații prin retele cu cablu'),
('612','Activități de telecomunicații prin retele fără cablu'),
('6120','Activități de telecomunicații prin retele fără cablu (exclusiv prin satelit)'),
('613','Activități de telecomunicații prin satelit'),
('6130','Activități de telecomunicații prin satelit'),
('619','Alte activități de telecomunicații'),
('6190','Alte activități de telecomunicații'),
('62','Activități de servicii în tehnologia informației'),
('620','Activități de servicii in tehnologia informatiei'),
('6201','Activități de realizare a soft-ului la comanda (software orientat client)'),
('6202','Activități de consultanta in tehnologia informatiei'),
('6203','Activități de management (gestiune si exploatare) a mijloacelor de calcul'),
('6209','Alte activități de servicii privind tehnologia informatiei'),
('63','Activități de servicii informatice'),
('631','Activități ale portalurilor web, prelucrarea datelor, administrarea paginilor web si activități conexe'),
('6311','Prelucrarea datelor, administrarea paginilor web si activități conexe'),
('6312','Activități ale portalurilor web'),
('639','Alte activități de servicii informaționale'),
('6391','Activități ale agențiilor de stiri'),
('6399','Alte activități de servicii informationale n.c.a.'),
('K','Intermedieri financiare și asigurări'),
('64','Intermedieri financiare, cu excepția activităților de asigurări și ale fondurilor de pensii'),
('641','Intermediere monetara'),
('6411','Activități ale bancii centrale (nationale)'),
('6419','Alte activități de intermedieri monetare'),
('642','Activități ale holdingurilor'),
('6420','Activități ale holdingurilor'),
('643','Fonduri mutuale si alte entități financiare similare'),
('6430','Fonduri mutuale si alte entități financiare similare'),
('649','Alte activități de intermedieri financiare, exclusiv activități de asigurări si fonduri de pensii'),
('6491','Leasing financiar'),
('6492','Alte activități de creditare'),
('6499','Alte intermedieri financiare n.c.a.'),
('65','Activități de asigurări, reasigurări și ale fondurilor de pensii (cu excepția celor din sistemul public de asigurări sociale)'),
('651','Activități de asigurări'),
('6511','Activități de asigurări de viata'),
('6512','Alte activități de asigurări (exceptand asigurările de viata)'),
('652','Activități de reasigurare'),
('6520','Activități de reasigurare'),
('653','Activități ale fondurilor de pensii (cu excepția celor din sistemul public de asigurări sociale)'),
('6530','Activități ale fondurilor de pensii (cu excepția celor din sistemul public de asigurări sociale)'),
('66','Activități auxiliare pentru intermedieri financiare, activități de asigurare și fonduri de pensii'),
('661','Activități auxiliare intermedierilor financiare, cu excepția activităților de asigurări si fonduri de pensii'),
('6611','Administrarea piețelor financiare'),
('6612','Activități de intermediere a tranzactiilor financiare'),
('6619','Activități auxiliare intermedierilor financiare, exclusiv activități de asigurări si fonduri de pensii'),
('662','Activități auxiliare de asigurări si fonduri de pensii'),
('6621','Activități de evaluare a riscului de asigurare si a pagubelor'),
('6622','Activități ale agenților si broker-ilor de asigurări'),
('6629','Alte activități auxiliare de asigurări si fonduri de pensii'),
('663','Activități de administrare a fondurilor'),
('6630','Activități de administrare a fondurilor'),
('L','Tranzacții imobiliare'),
('68','Tranzacții imobiliare'),
('681','Cumpararea si vânzarea de bunuri imobiliare proprii'),
('6810','Cumpararea si vânzarea de bunuri imobiliare proprii'),
('682','Inchirierea si subinchirierea bunurilor imobiliare proprii sau inchiriate'),
('6820','Inchirierea si subinchirierea bunurilor imobiliare proprii sau inchiriate'),
('683','Activități imobiliare pe baza de comision sau contract'),
('6831','Agentii imobiliare'),
('6832','Administrarea imobilelor pe baza de comision sau contract'),
('M','Activități profesionale, științifice și tehnice'),
('69','Activități juridice și de contabilitate'),
('691','Activități juridice'),
('6910','Activități juridice'),
('692','Activități de contabilitate si audit financiar; consultanta in domeniul fiscal'),
('6920','Activități de contabilitate si audit financiar; consultanta in domeniul fiscal'),
('70','Activități ale direcțiilor (centralelor), birourilor administrative centralizate; activități de management și de consultanță în management'),
('701','Activități ale directiilor (centralelor), birourilor administrative centralizate'),
('7010','Activități ale directiilor (centralelor), birourilor administrative centralizate'),
('702','Activități de consultanta in management'),
('7021','Activități de consultanta in domeniul relatiilor publice si al comunicarii'),
('7022','Activități de consultanta pentru afaceri si management'),
('71','Activități de arhitectură și inginerie; activități de testări și analiză tehnică'),
('711','Activități de arhitectura, inginerie si servicii de consultanta tehnica legate de acestea'),
('7111','Activități de arhitectura'),
('7112','Activități de inginerie si consultanta tehnica legate de acestea'),
('712','Activități de testari si analize tehnice'),
('7120','Activități de testari si analize tehnice'),
('72','Cercetare-dezvoltare'),
('721','Cercetare-dezvoltare in stiinte naturale si inginerie'),
('7211','Cercetare , dezvoltare in biotehnologie'),
('7219','Cercetare- dezvoltare in alte stiinte naturale si inginerie'),
('722','Cercetare-dezvoltare in stiinte sociale si umaniste'),
('7220','Cercetare- dezvoltare in stiinte sociale si umaniste'),
('73','Publicitate și activități de studiere a pieței'),
('731','Publicitate'),
('7311','Activități ale agențiilor de publicitate'),
('7312','Servicii de reprezentare media'),
('732','Activități de studiere a pieței si de sondare a opiniei publice'),
('7320','Activități de studiere a pieței si de sondare a opiniei publice'),
('74','Alte activități profesionale, științifice și tehnice'),
('741','Activități de design specializat'),
('7410','Activități de design specializat'),
('742','Activități fotografice'),
('7420','Activități fotografice'),
('743','Activități de traducere scrisă si orala (interpreti)'),
('7430','Activități de traducere scrisă si orala (interpreti)'),
('749','Alte activități profesionale, stiintifice si tehnice n.c.a.'),
('7490','Alte activități profesionale, stiintifice si tehnice n.c.a.'),
('75','Activități veterinare'),
('750','Activități veterinare'),
('7500','Activități veterinare'),
('N','Activități de servicii administrative și activități de servicii suport'),
('77','Activități de închiriere și leasing'),
('771','Activități de inchiriere si leasing cu autovehicule'),
('7711','Activități de inchiriere si leasing cu autoturisme si autovehicule rutiere usoare'),
('7712','Activități de inchiriere si leasing cu autovehicule rutiere grele'),
('772','Activități de inchiriere si leasing cu bunuri personale si gospodaresti'),
('7721','Activități de inchiriere si leasing cu bunuri recreationale si echipament sportiv'),
('7722','Inchirierea de casete video si discuri (CD-uri, DVD-uri)'),
('7729','Activități de inchiriere si leasing cu alte bunuri personale si gospodaresti n.c.a.'),
('773','Activități de inchiriere si leasing cu alte masini, echipamente si bunuri tangibile'),
('7731','Activități de inchiriere si leasing cu masini si echipamente agricole'),
('7732','Activități de inchiriere si leasing cu masini si echipamente pentru construcții'),
('7733','Activități de inchiriere si leasing cu masini si echipamente de birou (inclusiv calculatoare)'),
('7734','Activități de inchiriere si leasing cu masini si echipamente de transport pe apa'),
('7735','Activități de inchiriere si leasing cu masini si echipamente de transport aerian'),
('7739','Activități de inchiriere si leasing cu alte masini, echipamente si bunuri tangibile n.c.a.'),
('774','Leasing cu bunuri intangibile (exclusiv financiare)'),
('7740','Leasing cu bunuri intangibile (exclusiv financiare)'),
('78','Activități de servicii privind forța de muncă'),
('781','Activități ale agențiilor de plasare a forței de munca'),
('7810','Activități ale agențiilor de plasare a forței de munca'),
('782','Activități de contractare, pe baze temporare, a personalului'),
('7820','Activități de contractare, pe baze temporare, a personalului'),
('783','Servicii de furnizare si management a forței de munca'),
('7830','Servicii de furnizare si management a forței de munca'),
('79','Activități ale agențiilor turistice și a tur-operatorilor; alte servicii de rezervare și asistență turistică'),
('791','Activități ale agențiilor turistice si a tur-operatorilor'),
('7911','Activități ale agențiilor turistice'),
('7912','Activități ale tur-operatorilor'),
('799','Alte servicii de rezervare si asistenta turistica'),
('7990','Alte servicii de rezervare si asistenta turistica'),
('80','Activități de investigații și protecție'),
('801','Activități de protectie si garda'),
('8010','Activități de protectie si garda'),
('802','Activități de servicii privind sistemele de securizare'),
('8020','Activități de servicii privind sistemele de securizare'),
('803','Activități de investigații'),
('8030','Activități de investigații'),
('81','Activități de peisagistică și servicii pentru clădiri'),
('811','Activități de servicii suport combinate'),
('8110','Activități de servicii suport combinate'),
('812','Activități de curatenie'),
('8121','Activități generale de curatenie a cladirilor'),
('8122','Activități specializate de curatenie'),
('8129','Alte activități de curatenie'),
('813','Activități de intetinere peisagistica'),
('8130','Activități de intretinere peisagistica'),
('82','Activități de peisagistică și servicii pentru clădiri'),
('821','Activități de secretariat și servicii suport'),
('8211','Activități combinate de secretariat'),
('8219','Activități de fotocopiere, de pregatire a documentelor si alte activități specializate de secretariat'),
('822','Activități ale centrelor de intermediere telefonica (call center)'),
('8220','Activități ale centrelor de intermediere telefonica (call center)'),
('823','Activități de organizare a expozitiilor, targurilor si congreselor'),
('8230','Activități de organizare a expozitiilor, targurilor si congreselor'),
('829','Activități de servicii suport pentru intreprinderi n.c.a.'),
('8291','Activități ale agențiilor de colectare si a birourilor (oficiilor) de raportare a creditului'),
('8292','Activități de ambalare'),
('8299','Alte activități de servicii suport pentru intreprinderi n.c.a.'),
('O','Administrație publică și apărare; asigurări sociale din sistemul public'),
('84','Administrație publică și apărare; asigurări sociale din sistemul public'),
('841','Administratie publica generala, economica si sociala'),
('8411','Servicii de administratie publica generala'),
('8412','Reglementarea activităților organismelor care presteaza servicii in domeniul ingrijirii sanatatii, invatamantului, culturii si al altor activități sociale, exclusiv protectia sociala'),
('8413','Reglementarea si eficientizarea activităților economice'),
('842','Activități de servicii pentru societate'),
('8421','Activități de servicii externe'),
('8422','Activități de aparare nationala'),
('8423','Activități de justitie'),
('8424','Activități de ordine publica si de protectie civila'),
('8425','Activități de lupta impotriva incendiilor si de prevenire a acestora'),
('843','Activități de protectie sociala obligatorie'),
('8430','Activități de protectie sociala obligatorie'),
('P','Învățământ'),
('85','Învățământ'),
('851','Invatamant preșcolar'),
('8510','Invatamant preșcolar'),
('852','Invatamant primar'),
('8520','Invatamant primar'),
('853','Invatamant secundar'),
('8531','Invatamant secundar general'),
('8532','Invatamant secundar, tehnic sau profesional'),
('854','Invatamant superior'),
('8541','Invatamant superior non- universitar'),
('8542','Invatamant superior universitar'),
('855','Alte forme de invatamant'),
('8551','Invatamant in domeniul sportiv si recreational'),
('8552','Invatamant in domeniul cultural (limbi straine, muzica, teatru, dans, arte plastice, etc.)'),
('8553','Scoli de conducere (pilotaj)'),
('8559','Alte forme de invatamant n.c.a.'),
('856','Activități de servicii suport pentru invatamant'),
('8560','Activități de servicii suport pentru invatamant'),
('Q','Sănătate și asistență socială'),
('86','Activități referitoare la sănătatea umană'),
('861','Activități de asistenta spitaliceasca'),
('8610','Activități de asistenta spitaliceasca'),
('862','Activități de asistenta medicala ambulatorie si stomatologica'),
('8621','Activități de asistenta medicala generala'),
('8622','Activități de asistenta medicala specializata'),
('8623','Activități de asistenta stomatologica'),
('869','Alte activități referitoare la sanatatea umana'),
('8690','Alte activități referitoare la sanatatea umana'),
('87','Servicii combinate de îngrijire medicală și asistență socială, cu cazare'),
('871','Activități ale centrelor de ingrijire medicala'),
('8710','Activități ale centrelor de ingrijire medicala'),
('872','Activități ale centrelor de recuperare pshica si de dezintoxicare, exclusiv spitale'),
('8720','Activități ale centrelor de recuperare psihica si de dezintoxicare, exclusiv spitale'),
('873','Activități ale caminelor de bătrâni si ale caminelor pentru persoane aflate in incapacitate de a se ingriji singure'),
('8730','Activități ale caminelor de bătrâni si ale caminelor pentru persoane aflate in incapacitate de a se ingriji singure'),
('879','Alte activități de asistenta sociala, cu cazare n.c.a.'),
('8790','Alte activități de asistenta sociala, cu cazare n.c.a.'),
('88','Activități de asistență socială, fără cazare'),
('881','Activități de asistenta sociala, fără cazare, pentru bătrâni si pentru persoane aflate in incapacitate de a se ingriji singure'),
('8810','Activități de asistenta sociala, fără cazare, pentru bătrâni si pentru persoane aflate in incapacitate de a se ingriji singure'),
('889','Alte activități de asistenta sociala, fără cazare'),
('8891','Activități de ingrijire zilnica pentru copii'),
('8899','Alte activități de asistenta sociala, fără cazare, n.c.a.'),
('R','Activitați de spectacole, culturale și recreative'),
('90','Activități de creație și interpretare artistică'),
('900','Activități de creație si interpretare artistica'),
('9001','Activități de interpretare artistica (spectacole)'),
('9002','Activități suport pentru interpretare artistica (spectacole)'),
('9003','Activități de creație artistica'),
('9004','Activități de gestionare a salilor de spectacole'),
('91','Activități ale bibliotecilor, arhivelor, muzeelor și alte activități culturale'),
('910','Activități ale bibliotecilor, arhivelor, muzeelor si alte activități culturale'),
('9101','Activități ale bibliotecilor si arhivelor'),
('9102','Activități ale muzeelor'),
('9103','Gestionarea monumentelor, cladirilor istorice si a altor obiective de interes turistic'),
('9104','Activități ale gradinilor zoologice, botanice si ale rezervatiilor naturale'),
('92','Activități de jocuri de noroc și pariuri'),
('920','Activități de jocuri de noroc si pariuri'),
('9200','Activități de jocuri de noroc si pariuri'),
('93','Activități sportive, recreative și distractive'),
('931','Activități sportive'),
('9311','Activități ale bazelor sportive'),
('9312','Activități ale cluburilor sportive'),
('9313','Activități ale centrelor de fitness'),
('9319','Alte activități sportive'),
('932','Alte activități recreative si distractive'),
('9321','Bâlciuri si parcuri de distracții'),
('9329','Alte activități recreative si distractive n.c.a.'),
('S','Alte activități de servicii'),
('94','Activități asociative diverse'),
('941','Activități ale organizatiilor economice, patronale si profesionale'),
('9411','Activități ale organizatiilor economice si patronale'),
('9412','Activități ale organizatiilor profesionale'),
('942','Activități ale sindicatelor salariatilor'),
('9420','Activități ale sindicatelor salariatilor'),
('949','Alte activități asociative'),
('9491','Activități ale organizatiilor religioase'),
('9492','Activități ale organizatiilor politice'),
('9499','Activități ale altor organizatii n.c.a.'),
('95','Reparații de calculatoare, de articole personale și de uz gospodăresc'),
('951','Repararea calculatoarelor si a echipamentelor de comunicații'),
('9511','Repararea calculatoarelor si a echipamentelor periferice'),
('9512','Repararea echipamentelor de comunicații'),
('952','Reparatii de articole personale si de uz gospodaresc'),
('9521','Repararea aparatelor electronice de uz casnic'),
('9522','Repararea dispozitivelor de uz gospodaresc si a echipamentelor pentru casa si gradina'),
('9523','Repararea incaltamintei si a articolelor din piele'),
('9524','Repararea mobilei si a furniturilor casnice'),
('9525','Repararea ceasurilor si a bijuteriilor'),
('9529','Repararea articolelor de uz personal si gospodaresc n.c.a.'),
('96','Alte activități de servicii'),
('960','Alte activități de servicii'),
('9601','Spalarea si curatarea (uscata) articolelor textile si a produselor din blana'),
('9602','Coafura si alte activități de infrumusetare'),
('9603','Activități de pompe funebre si similare'),
('9604','Activități de intretinere corporala'),
('9609','Alte activități de servicii n.c.a.'),
('T','Activități ale gospodăriilor private în calitate de angajator de personal casnic; activități ale gospodăriilor private de producere de bunuri și servicii destinate consumului propriu'),
('97','Activități ale gospodăriilor private în calitate de angajator de personal casnic'),
('970','Activități ale gospodariilor private in calitate de angajator de personal casnic'),
('9700','Activități ale gospodariilor private in calitate de angajator de personal casnic'),
('98','Activități ale gospodăriilor private de producere de bunuri și servicii destinate consumului propriu'),
('981','Activități ale gospodariilor private de producere de bunuri destinate consumului propriu'),
('9810','Activități ale gospodariilor private de producere de bunuri destinate consumului propriu'),
('982','Activități ale gospodariilor private de producere de servicii pentru scopuri proprii'),
('9820','Activități ale gospodariilor private de producere de servicii pentru scopuri proprii'),
('U','Activități ale organizațiilor și organismelor extrateritoriale'),
('99','Activități ale organizațiilor și organismelor extrateritoriale'),
('990','Activități ale organizatiilor si organismelor extrateritoriale'),
('9900','Activități ale organizatiilor si organismelor extrateritoriale');
CREATE INDEX idx_caen_code ON public.caen (code);

CREATE INDEX IF NOT exists idx_caen_code ON public.caen (code);
